# Generated by Django 2.1.1 on 2018-10-22 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0003_auto_20181022_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 31, 22, 268944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 31, 22, 268995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 31, 22, 269565, tzinfo=utc)),
        ),
    ]
