# Generated by Django 2.1.1 on 2018-10-20 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0002_auto_20181020_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 10, 24, 5, 868219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 10, 24, 5, 868265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 10, 24, 5, 868724, tzinfo=utc)),
        ),
    ]
