# Generated by Django 2.1 on 2018-08-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0003_auto_20180815_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverSheetForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZeroDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='zero_descriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalwellbeing.ZeroDescriptor'),
        ),
    ]
