# Generated by Django 2.1 on 2018-08-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0004_auto_20180816_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchers',
            name='firstname',
            field=models.CharField(default='broken', max_length=30),
        ),
        migrations.AddField(
            model_name='researchers',
            name='surname',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
