# Generated by Django 2.1 on 2018-08-20 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animalwellbeing', '0005_auto_20180820_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='coversheetform',
            name='creator',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
