# Generated by Django 2.1 on 2018-08-20 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0010_auto_20180820_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='coversheetform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 7, 39, 40, 847034)),
        ),
    ]
