# Generated by Django 2.1 on 2018-08-20 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0012_auto_20180820_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 7, 49, 41, 530640)),
        ),
        migrations.AlterField(
            model_name='coversheetform',
            name='name',
            field=models.CharField(default='<django.db.models.fields.related.OneToOneField>__form#<built-in function id>', max_length=30),
        ),
    ]
