# Generated by Django 2.1 on 2018-08-20 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0013_auto_20180820_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 8, 58, 0, 486090)),
        ),
    ]
