# Generated by Django 2.1 on 2018-08-20 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0014_auto_20180820_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 11, 55, 40, 333646)),
        ),
    ]
