# Generated by Django 2.1 on 2018-08-23 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0015_auto_20180820_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 23, 10, 8, 10, 373379)),
        ),
    ]
