# Generated by Django 2.1 on 2018-08-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0016_auto_20180823_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 24, 16, 41, 26, 721267)),
        ),
    ]
