# Generated by Django 2.1 on 2018-09-01 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0017_auto_20180824_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverSheetFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_data', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('created_at', models.DateField(default=datetime.datetime(2018, 9, 1, 17, 45, 53, 34596))),
                ('name', models.CharField(default='<django.db.models.fields.related.OneToOneField>__form#<built-in function id>', max_length=30)),
                ('creator', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='animalwellbeing.Researchers')),
            ],
        ),
        migrations.RemoveField(
            model_name='coversheetform',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='supervisors',
            name='user',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='zero_descriptor',
        ),
        migrations.DeleteModel(
            name='CoverSheetForm',
        ),
        migrations.DeleteModel(
            name='Supervisors',
        ),
        migrations.DeleteModel(
            name='ZeroDescriptor',
        ),
    ]
