# Generated by Django 2.1 on 2018-09-05 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0018_auto_20180901_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 15, 34, 47, 897231)),
        ),
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='name',
            field=models.CharField(default='coversheet__form#<built-in function id>', max_length=30),
        ),
    ]
