# Generated by Django 2.1 on 2018-09-05 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0020_auto_20180905_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 15, 57, 57, 695584)),
        ),
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='name',
            field=models.CharField(default='coversheetform_#test', max_length=30),
        ),
    ]
