# Generated by Django 2.1 on 2018-09-05 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalwellbeing', '0022_auto_20180905_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchers',
            name='number_of_coversheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coversheetformmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 16, 24, 24, 205565)),
        ),
    ]
